# Generated by Django 4.0.5 on 2024-05-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='dt_created',
            field=models.DateField(verbose_name='Date Created'),
        ),
    ]
