# Generated by Django 4.0.5 on 2024-05-13 06:15

import datetime
import diary.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_page_dt_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 6, 15, 37, 41829, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(validators=[diary.validators.validate_no_hash]),
        ),
        migrations.AlterField(
            model_name='page',
            name='feeling',
            field=models.CharField(max_length=80, validators=[diary.validators.validate_no_numbers]),
        ),
        migrations.AlterField(
            model_name='page',
            name='score',
            field=models.IntegerField(validators=[diary.validators.validate_score]),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=100, validators=[diary.validators.validate_no_hash]),
        ),
    ]
