# Generated by Django 4.0.5 on 2024-05-13 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_page_date_alter_page_content_alter_page_feeling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 13)),
        ),
    ]
