# Generated by Django 4.0.5 on 2024-05-13 06:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_alter_page_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 6, 17, 46, 53225, tzinfo=utc)),
        ),
    ]
