# Generated by Django 4.0.5 on 2024-05-13 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_alter_page_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 13), verbose_name='Date Real'),
        ),
    ]
